FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["GamedevQuest/GamedevQuest.csproj", "GamedevQuest/"]
RUN dotnet restore "./GamedevQuest/GamedevQuest.csproj"
COPY . .
WORKDIR "/src/GamedevQuest"
RUN dotnet build "GamedevQuest.csproj" -c $BUILD_CONFIGURATION -o /app/build
FROM build AS publish
RUN dotnet publish "GamedevQuest.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GamedevQuest.dll"]